language: node_js
sudo: false

node_js:
  # Use the explicit NodeJS LTS version (https://github.com/nodejs/Release#release-schedule) to avoid any
  # automatic upgrade of the version. This ensures that all Travis jobs run consistently and don't have
  # different Node versions.
  - '12.14.1'

branches:
  only:
    - master

addons:
  chrome: stable

install:
  - yarn

script:
  - ./scripts/ci/deploy-cn.sh
